name: List services in GCP
on:
 push
 
permissions:
  id-token: write
  contents: read

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - run: env
    - run: |
        OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=minty.exit.o6s.io" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
        JWT=$(echo $OIDC_TOKEN | jq -j '.value'| base64)
        echo $JWT
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/693638754866/locations/global/workloadIdentityPools/github-general/providers/github-general-provider'
          service_account: 'test-storage-sa@ag-workload-identity-github.iam.gserviceaccount.com'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list
